# Generated by Django 3.1.12 on 2025-09-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='risk_level',
            field=models.CharField(max_length=50),
        ),
    ]
